### ISSUE TITLE
Cell diff stays 0.000V when using manual config

### ISSUE THREAD

**Issue by DutchKillerbee** [Pho3niX90/jk-bms-card#6]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

First of all thanks for your effort.
I am (miss) using your card for my heltec balancers
I noticed that the cell diff stays zero.
![Image](https://github.com/user-attachments/assets/f779458c-1033-450c-9e01-5dbcac18dbd3)
I tried to configure a min_voltage_cell and max_voltage_cell sensor but than also the min/max color doesn't work.

Is this a calculated value?

### Expected behaviour

Cell difference is calculated. Max - min voltage or a sensor configuration

### Card Version

1.1.2

### Home Assistant Version

2025.6.0

### Configuration

```shell
type: custom:jk-bms-card
cellCount: 16
cellColumns: 2
cellLayout: bankMode
entities:
  balancing_current: sensor.heltec_master_balancing_current
  power: sensor.victron_ess_battery_load
  balance_trigger_voltage: ""
  total_runtime_formatted: sensor.heltec_master_total_runtime_formatted
  charging: sensor.victron_ess_total_battery_in
  discharging: sensor.victron_ess_total_battery_out
  balancer: binary_sensor.heltec_master_balancing
  total_voltage: sensor.heltec_master_total_voltage
  total_battery_capacity_setting: ""
  total_charging_cycle_capacity: ""
  average_cell_voltage: sensor.heltec_master_average_cell_voltage
  current: sensor.victron_ess_battery_current
  state_of_charge: sensor.victron_ess_battery_percent
  capacity_remaining: ""
  charging_cycles: ""
  power_tube_temperature: sensor.heltec_master_temperature_sensor_1
  min_voltage_cell: null
  max_voltage_cell: null
  errors: ""
  cell_voltage_1: sensor.heltec_master_voltage_01
  cell_voltage_2: sensor.heltec_master_voltage_02
  cell_voltage_3: sensor.heltec_master_voltage_03
  cell_voltage_4: sensor.heltec_master_voltage_04
  cell_voltage_5: sensor.heltec_master_voltage_05
  cell_voltage_6: sensor.heltec_master_voltage_06
  cell_voltage_7: sensor.heltec_master_voltage_07
  cell_voltage_8: sensor.heltec_master_voltage_08
  cell_voltage_9: sensor.heltec_master_voltage_09
  cell_voltage_10: sensor.heltec_master_voltage_10
  cell_voltage_11: sensor.heltec_master_voltage_11
  cell_voltage_12: sensor.heltec_master_voltage_12
  cell_voltage_13: sensor.heltec_master_voltage_13
  cell_voltage_14: sensor.heltec_master_voltage_14
  cell_voltage_15: sensor.heltec_master_voltage_15
  cell_voltage_16: sensor.heltec_master_voltage_16
  cell_resistance_1: sensor.heltec_master_resistance_01
  cell_resistance_2: sensor.heltec_master_resistance_02
  cell_resistance_3: sensor.heltec_master_resistance_03
  cell_resistance_4: sensor.heltec_master_resistance_04
  cell_resistance_5: sensor.heltec_master_resistance_05
  cell_resistance_6: sensor.heltec_master_resistance_06
  cell_resistance_7: sensor.heltec_master_resistance_07
  cell_resistance_8: sensor.heltec_master_resistance_08
  cell_resistance_9: sensor.heltec_master_resistance_09
  cell_resistance_10: sensor.heltec_master_resistance_10
  cell_resistance_11: sensor.heltec_master_resistance_11
  cell_resistance_12: sensor.heltec_master_resistance_12
  cell_resistance_13: sensor.heltec_master_resistance_13
  cell_resistance_14: sensor.heltec_master_resistance_14
  cell_resistance_15: sensor.heltec_master_resistance_15
  cell_resistance_16: sensor.heltec_master_resistance_16
title: Heltec Master
```

### Relevant log output

```shell

```

**Comment by DutchKillerbee** [comment]
Hello

I am using the latest version and still the Delta V remains 0.

<img width="433" height="236" alt="Image" src="https://github.com/user-attachments/assets/392a0515-8370-41ce-be26-29027ea9bc26" />

this is my configuration:

```
type: custom:jk-bms-card
cellCount: 16
cellColumns: 2
cellLayout: bankMode
entities:
  balancing_current: sensor.heltec_master_balancing_current
  power: sensor.victron_ess_battery_load
  balance_trigger_voltage: ""
  total_runtime_formatted: sensor.heltec_master_total_runtime_formatted
  charging: sensor.victron_ess_total_battery_in
  discharging: sensor.victron_ess_total_battery_out
  balancer: binary_sensor.heltec_master_balancing
  total_voltage: sensor.heltec_master_total_voltage
  total_battery_capacity_setting: ""
  total_charging_cycle_capacity: ""
  average_cell_voltage: sensor.heltec_master_average_cell_voltage
  current: sensor.victron_ess_battery_current
  state_of_charge: sensor.victron_ess_battery_percent
  capacity_remaining: ""
  charging_cycles: ""
  power_tube_temperature: sensor.heltec_master_temperature_sensor_1
  min_voltage_cell: sensor.heltec_master_min_cell_voltage
  max_voltage_cell: sensor.heltec_master_max_cell_voltage
  errors: ""
  cell_voltage_1: sensor.heltec_master_voltage_01
  cell_voltage_2: sensor.heltec_master_voltage_02
  cell_voltage_3: sensor.heltec_master_voltage_03
  cell_voltage_4: sensor.heltec_master_voltage_04
  cell_voltage_5: sensor.heltec_master_voltage_05
  cell_voltage_6: sensor.heltec_master_voltage_06
  cell_voltage_7: sensor.heltec_master_voltage_07
  cell_voltage_8: sensor.heltec_master_voltage_08
  cell_voltage_9: sensor.heltec_master_voltage_09
  cell_voltage_10: sensor.heltec_master_voltage_10
  cell_voltage_11: sensor.heltec_master_voltage_11
  cell_voltage_12: sensor.heltec_master_voltage_12
  cell_voltage_13: sensor.heltec_master_voltage_13
  cell_voltage_14: sensor.heltec_master_voltage_14
  cell_voltage_15: sensor.heltec_master_voltage_15
  cell_voltage_16: sensor.heltec_master_voltage_16
  cell_resistance_1: sensor.heltec_master_resistance_01
  cell_resistance_2: sensor.heltec_master_resistance_02
  cell_resistance_3: sensor.heltec_master_resistance_03
  cell_resistance_4: sensor.heltec_master_resistance_04
  cell_resistance_5: sensor.heltec_master_resistance_05
  cell_resistance_6: sensor.heltec_master_resistance_06
  cell_resistance_7: sensor.heltec_master_resistance_07
  cell_resistance_8: sensor.heltec_master_resistance_08
  cell_resistance_9: sensor.heltec_master_resistance_09
  cell_resistance_10: sensor.heltec_master_resistance_10
  cell_resistance_11: sensor.heltec_master_resistance_11
  cell_resistance_12: sensor.heltec_master_resistance_12
  cell_resistance_13: sensor.heltec_master_resistance_13
  cell_resistance_14: sensor.heltec_master_resistance_14
  cell_resistance_15: sensor.heltec_master_resistance_15
  cell_resistance_16: sensor.heltec_master_resistance_16
title: Heltec Master
```
